### ISSUE TITLE
Unable to read ACS papers

### ISSUE THREAD

**Issue by Domeml94** [ShuHuang/batterydatabase#1]
Hi there, 
I was testing the following paper earlier: DOI: 10.1021/acsami.5b02724

After running `extract.py` I get the error: 
```
  File "C:\Users\User\PycharmProjects\batterydatabase_JLU\database.py", line 68, in extract
      "specifier": dicts["specifier"]}, "metadata": dic['metadata']}
  KeyError: 'metadata'
```

Is this a known/common error when using ACS papers? 
Any advice is greatly appreciated!

**Comment by ShuHuang** [comment]
Hi thanks for your question. Could you please tell me which ACS journal are you trying to analyse? Normally it works well with papers from RSC, Elsevier and some of Springer. ACS can propably work but maybe need some modifications of code. I will have a look. Thanks!

**Comment by Domeml94** [comment]
Thanks for your quick response. The paper that I was testing is published in ACS Applied Materials & Interfaces.

**Comment by ShuHuang** [comment]
Hi! Sorry as we don't have access to the ACS database, I still can't find the html/xml of your paper (DOI: 10.1021/acsami.5b02724). Which format are you using? The metadata KeyError means that ChemDataExtractor can't find the meta information of ACS paper, e.g. DOI, title, journal, etc. However, if you just delete this key and value pair in database.py, this KeyError should be fixed.

**Comment by Domeml94** [comment]
Ok, thanks for this tip. I'm gonna test a few additional things. Here is also another paper with the same issue: https://doi.org/10.1021/acsomega.7b00379 This one should be open-access.
